exports.seed = async function (knex) {
  await knex("tickets").del();
  await knex("tickets").insert([
    {
      ticket_id: 1,
      title: "Unable to connect to VPN",
      description: "The VPN connection fails with an error.",
      contact_user_id: 10,
      created_date: "2024-08-01 09:00:00",
      closed_date: null,
    },
    {
      ticket_id: 2,
      title: "Printer not working",
      description: "The office printer is not responding.",
      contact_user_id: 10,
      created_date: "2024-08-01 10:30:00",
      closed_date: "2024-08-03 12:00:00",
    },
    {
      ticket_id: 3,
      title: "Slow internet connection",
      description: "The internet connection is very slow.",
      contact_user_id: 10,
      created_date: "2024-08-02 08:45:00",
      closed_date: null,
    },
    {
      ticket_id: 4,
      title: "Software installation request",
      description: "Request to install Adobe Photoshop.",
      contact_user_id: 10,
      created_date: "2024-08-02 11:00:00",
      closed_date: "2024-08-04 09:00:00",
    },
    {
      ticket_id: 5,
      title: "Email not syncing",
      description: "Outlook is not syncing emails properly.",
      contact_user_id: 10,
      created_date: "2024-08-02 14:15:00",
      closed_date: "2024-08-05 10:00:00",
    },
    {
      ticket_id: 6,
      title: "Laptop overheating",
      description: "Laptop is getting very hot during use.",
      contact_user_id: 11,
      created_date: "2024-08-03 09:00:00",
      closed_date: null,
    },
    {
      ticket_id: 7,
      title: "Can't access shared drive",
      description: "Unable to access the shared network drive.",
      contact_user_id: 11,
      created_date: "2024-08-03 10:00:00",
      closed_date: null,
    },
    {
      ticket_id: 8,
      title: "Computer won't boot",
      description: "The computer is stuck on the boot screen.",
      contact_user_id: 11,
      created_date: "2024-08-04 08:00:00",
      closed_date: null,
    },
    {
      ticket_id: 9,
      title: "Password reset request",
      description: "Forgotten password, need to reset.",
      contact_user_id: 11,
      created_date: "2024-08-04 09:15:00",
      closed_date: "2024-08-04 10:00:00",
    },
    {
      ticket_id: 10,
      title: "Monitor flickering",
      description: "The monitor flickers randomly.",
      contact_user_id: 11,
      created_date: "2024-08-05 08:30:00",
      closed_date: null,
    },
    {
      ticket_id: 11,
      title: "Unable to install software update",
      description: "Error when trying to install the latest software update.",
      contact_user_id: 12,
      created_date: "2024-08-05 11:00:00",
      closed_date: null,
    },
    {
      ticket_id: 12,
      title: "Wireless mouse not working",
      description: "The wireless mouse is not responding.",
      contact_user_id: 12,
      created_date: "2024-08-05 13:00:00",
      closed_date: "2024-08-06 10:00:00",
    },
    {
      ticket_id: 13,
      title: "Security alert on laptop",
      description: "A security alert keeps popping up.",
      contact_user_id: 12,
      created_date: "2024-08-06 09:00:00",
      closed_date: null,
    },
    {
      ticket_id: 14,
      title: "Headphones not working",
      description: "The headphones are not being detected by the computer.",
      contact_user_id: 12,
      created_date: "2024-08-06 10:30:00",
      closed_date: null,
    },
    {
      ticket_id: 15,
      title: "Touchpad issues",
      description: "The laptop touchpad is unresponsive.",
      contact_user_id: 12,
      created_date: "2024-08-06 12:00:00",
      closed_date: null,
    },
    {
      ticket_id: 16,
      title: "System crash",
      description: "The system crashes frequently.",
      contact_user_id: 13,
      created_date: "2024-08-07 08:00:00",
      closed_date: null,
    },
    {
      ticket_id: 17,
      title: "Wi-Fi connection drops",
      description: "The Wi-Fi connection keeps dropping.",
      contact_user_id: 13,
      created_date: "2024-08-07 10:00:00",
      closed_date: null,
    },
    {
      ticket_id: 18,
      title: "External hard drive not detected",
      description: "The external hard drive is not detected by the computer.",
      contact_user_id: 13,
      created_date: "2024-08-07 11:00:00",
      closed_date: null,
    },
    {
      ticket_id: 19,
      title: "Broken laptop screen",
      description: "The laptop screen is cracked.",
      contact_user_id: 13,
      created_date: "2024-08-08 08:00:00",
      closed_date: null,
    },
    {
      ticket_id: 20,
      title: "Bluetooth not working",
      description: "Bluetooth devices are not connecting.",
      contact_user_id: 13,
      created_date: "2024-08-08 09:30:00",
      closed_date: null,
    },
    {
      ticket_id: 21,
      title: "Unable to access email",
      description: "Email account is locked.",
      contact_user_id: 14,
      created_date: "2024-08-08 11:00:00",
      closed_date: "2024-08-09 09:00:00",
    },
    {
      ticket_id: 22,
      title: "Projector not working",
      description: "The office projector is not displaying anything.",
      contact_user_id: 14,
      created_date: "2024-08-08 13:00:00",
      closed_date: null,
    },
    {
      ticket_id: 23,
      title: "Can’t print from phone",
      description: "Unable to print documents from mobile devices.",
      contact_user_id: 14,
      created_date: "2024-08-09 08:00:00",
      closed_date: null,
    },
    {
      ticket_id: 24,
      title: "Keyboard not working",
      description: "The keyboard keys are unresponsive.",
      contact_user_id: 14,
      created_date: "2024-08-09 09:00:00",
      closed_date: null,
    },
    {
      ticket_id: 25,
      title: "Slow computer performance",
      description: "The computer is running very slowly.",
      contact_user_id: 14,
      created_date: "2024-08-09 10:30:00",
      closed_date: null,
    },
    {
      ticket_id: 26,
      title: "Software crash",
      description: "The software crashes when opening.",
      contact_user_id: 15,
      created_date: "2024-08-09 12:00:00",
      closed_date: null,
    },
    {
      ticket_id: 27,
      title: "System won’t shut down",
      description: "The system is not shutting down properly.",
      contact_user_id: 15,
      created_date: "2024-08-09 13:00:00",
      closed_date: null,
    },
    {
      ticket_id: 28,
      title: "Can’t connect to network",
      description: "Unable to connect to the corporate network.",
      contact_user_id: 15,
      created_date: "2024-08-10 08:00:00",
      closed_date: null,
    },
    {
      ticket_id: 29,
      title: "Sound issues",
      description: "No sound is coming from the speakers.",
      contact_user_id: 15,
      created_date: "2024-08-10 09:00:00",
      closed_date: null,
    },
    {
      ticket_id: 30,
      title: "Battery not charging",
      description: "The laptop battery is not charging.",
      contact_user_id: 15,
      created_date: "2024-08-10 10:00:00",
      closed_date: null,
    },
  ]);
};
